# Generated by Django 4.2 on 2024-04-09 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('computer_store', '0002_alter_cartmodel_id_alter_productmodel_id'),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE PROCEDURE cart_get_all_by_user_id(user_id int)
            BEGIN
                SELECT
                    p.name, 
                    p.image_url,
                    p.price,
                    c.total_order 
                FROM computer_store_productmodel AS p 
                INNER JOIN computer_store_cartmodel AS c ON p.id = c.product_id
                WHERE c.user_id = user_id;
            END
            """
        )
    ]
