# Generated by Django 4.2 on 2024-04-22 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('computer_store', '0005_auto_20240410_1052'),
    ]

    operations = [
        migrations.RunSQL(
            '''
                DELETE FROM `auth_user`
                WHERE id = 9999

                INSERT INTO `auth_user`
                (`id`,
                `password`,
                `last_login`,
                `is_superuser`,
                `username`,
                `first_name`,
                `last_name`,
                `email`,
                `is_staff`,
                `is_active`,
                `date_joined`)
                VALUES
                (9999,
                'pbkdf2_sha256$600000$JP9BmN8ESUAegYOHfehcvV$Gz7XC1CwDAP31RMRAjXsbJ9a7cV2pnAxEoJiltNshY0=',
                null,
                0,
                'demo_user1',
                '',
                '',
                'demo_user1@gmail.com',
                0,
                1,
                '2024-04-09 02:57:46.407869');

            '''
        )
    ]
