# Generated by Django 4.2 on 2024-04-29 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('computer_store', '0006_auto_20240422_1146'),
    ]

    operations = [
        migrations.RunSQL(
            """
                DROP PROCEDURE IF EXISTS profile_delete_user_by_user_id;
                CREATE PROCEDURE profile_delete_user_by_user_id(user_id int)
                BEGIN
                    DELETE FROM computer_store_cartmodel
                    where user_id = user_id;      
                END
            """
        )
    ]
