# Generated by Django 4.2 on 2024-05-14 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('computer_store', '0011_auto_20240510_1206'),
    ]

    operations = [
        migrations.RunSQL(
            """
                DROP PROCEDURE IF EXISTS cart_product_update_by_id;
                CREATE PROCEDURE cart_product_update_by_id(in_id VARCHAR(32), in_total_order INT)
                BEGIN
                    UPDATE computer_store_cartmodel
                    SET total_order = in_total_order
                    WHERE id = in_id;
                END
            """
        )
    ]
