# Generated by Django 4.2 on 2024-05-16 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('computer_store', '0013_auto_20240516_1008'),
    ]

    operations = [
       migrations.RunSQL(
            '''
                DELETE FROM `auth_user`
                WHERE id = 9998;

                INSERT INTO `auth_user`
                (`id`,
                `password`,
                `last_login`,
                `is_superuser`,
                `username`,
                `first_name`,
                `last_name`,
                `email`,
                `is_staff`,
                `is_active`,
                `date_joined`)
                VALUES
                (9998,
                'pbkdf2_sha256$600000$JP9BmN8ESUAegYOHfehcvV$Gz7XC1CwDAP31RMRAjXsbJ9a7cV2pnAxEoJiltNshY0=',
                null,
                1,
                'admin_kita',
                '',
                '',
                'admin_kita@gmail.com',
                0,
                1,
                '2024-04-09 02:57:46.407869');

            '''
        )
    ]
