# Generated by Django 4.2 on 2024-05-20 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computer_store', '0014_auto_20240516_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
