# Generated by Django 4.2 on 2024-06-06 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computer_store', '0015_productmodel_is_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
