# Generated by Django 4.2 on 2024-06-06 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computer_store', '0016_productmodel_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
